[package]
name = "autovec_demo"
version = "1.0.0"
authors = ["Nick Wilcox <nick@nickwilcox.com>"]
edition = "2018"


[build-dependencies]
cc = "1.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmark"
harness = false
